### ISSUE TITLE
Using incorrect name of MassiveCore plugin

### ISSUE THREAD

**Issue by adventurerok** [boy0001/WorldeditRegions#3]
When checking for factions, you check for a plugin called "mcore" to see if the factions plugin is old or new. As "mcore" was renamed to "MassiveCore" in July 2014, the plugin fails to detect "mcore" and assumes I am using the old factions, causing many NPEs as it tries to reference objects in the old factions to spam my console.

To fix, this, add

``` java
if(mCorePlugin == null) mCorePlugin = getServer().getPluginManager().getPlugin("MassiveCore");
```

after the line

``` java
Plugin mCorePlugin = getServer().getPluginManager().getPlugin("mcore");
```

**Comment by cfairweather** [comment]
Why don't you make this fix for him and the send a pull request?
